# Generated by Django 4.1.3 on 2022-12-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrderManagement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
