# Generated by Django 4.1.3 on 2022-12-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrderManagement", "0002_order_paid_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
