# Generated by Django 4.1.3 on 2023-03-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrderManagement", "0003_orderitem_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="Product_title",
            field=models.CharField(default="Product Tile Not Found", max_length=100),
        ),
    ]
