# Generated by Django 4.1.3 on 2022-11-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopvendorprofile",
            name="vendorname",
            field=models.CharField(default="Null", max_length=100),
        ),
    ]
