# Generated by Django 4.1.3 on 2022-11-29 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField()),
                ("is_active", models.BooleanField()),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("product_slug", models.SlugField()),
                ("color", models.CharField(max_length=10)),
                ("Style", models.CharField(blank=True, max_length=100, null=True)),
                ("Pattern", models.CharField(blank=True, max_length=100, null=True)),
                ("shape", models.CharField(blank=True, max_length=100, null=True)),
                ("Product_category", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("qty", models.IntegerField()),
                ("brand_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "available_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("in_stock", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "categoryfk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="inventory.category",
                    ),
                ),
                (
                    "vendorfk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="account.shopvendorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "products",
                "ordering": ["-date_added"],
            },
        ),
    ]
