# Generated by Django 4.1.3 on 2022-12-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="latitude",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="longitude",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
