# Generated by Django 4.1.3 on 2023-03-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_product_latitude_product_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="category_images"),
        ),
        migrations.AlterField(
            model_name="product",
            name="available_location",
            field=models.CharField(
                blank=True, default="Blue area Islamabad", max_length=100, null=True
            ),
        ),
    ]
